### ISSUE TITLE
win32

### ISSUE THREAD

**Issue by geraldstanje** [chai2010/qml#1]
hi,

does it also support windows 7, x32?

Thanks,
-Gerald

**Comment by chai2010** [comment]
I think it can also work on win32,
but i donot test it.

**Comment by geraldstanje** [comment]
whats the difference between this project and the https://github.com/go-qml/qml ?
the original version doesnt work on windows?

**Comment by chai2010** [comment]
The original go-qml use static link with gcc,
only support Qt/MinGW, can't work with Qt/MSVC.

And the Qt64bit only have MSVC version,
see http://qt-project.org/downloads

**Comment by oldtree2008** [comment]
![error](https://cloud.githubusercontent.com/assets/5414588/4586645/a3898fba-501b-11e4-83ec-f3d12f46b045.png)
I tried in window7. mingw and msvs sdk. but it failed.

**Comment by geraldstanje** [comment]
hi, can you test this repo? https://github.com/go-qml/qml

**Comment by oldtree2008** [comment]
I test ,but it failed too. I don't know why

**Comment by geraldstanje** [comment]
could you plase use gdb to figure out where it crashes in order to fix the bug!? maybe it relates to this issue: https://github.com/go-qml/qml/issues/109

**Comment by chai2010** [comment]
@geraldstanje
I test `chai2010/qml/hello.go` with Qt5.3.2-msvc2012-win32, it can works.

**Comment by chai2010** [comment]
@oldtree2008 You should make sure all `env` are valid.
If you first install Qt/MinGW, you need restart system.
And suggest use `go run hello.go` in command line (also need `env` valid).

**Comment by chai2010** [comment]
@geraldstanje 

I try to build `chai2010/qml/internal/goqml` with Qt5.2.1-mingw32, failed!
I donot try build `go-qml/qml`.

I think Qt5/MinGW is not a good choise right now (I only use Go64bit and Qt/MSVC).

**Comment by oldtree2008** [comment]
@chai2010  I tried with Qt5.3.2-msvc2012-win32. but run hello . it failed. just like screenshot posted by me last time.

**Comment by oldtree2008** [comment]
@chai2010  I also tried with Qt5.3.2-msvc2013-win32 , Qt5.3.2-msvc2012-win32,qt-windows-opensource-5.0.2-msvc2010_32-x86. but all failed .  my OS is win7.  golang 1.3. something wrong ?  

running hello.exe  returns 'exit status 255'

**Comment by chai2010** [comment]
@oldtree2008 

Can you give more details?
1. `go version` and `go env`
2. `qmake -v`
3. `gcc -v`
4. `nmake /?`
5. `echo %GOROOT% %QTDIR% %PATH%`
6. ?

And you can use `Depends` tool to check the target depends.
http://www.dependencywalker.com/

Thanks!

**Comment by oldtree2008** [comment]
@chai2010 

![a](https://cloud.githubusercontent.com/assets/5414588/4601854/6b7eb230-511a-11e4-9b71-4ed5d2fadfb9.png)
![b](https://cloud.githubusercontent.com/assets/5414588/4601857/8c0a3cfe-511a-11e4-8c54-508df74f6284.png)
![c](https://cloud.githubusercontent.com/assets/5414588/4601859/92346ea6-511a-11e4-8bf0-6b735da51c39.png)

![d](https://cloud.githubusercontent.com/assets/5414588/4601889/4d5414ca-511b-11e4-9737-b1822bcac546.png)

**Comment by oldtree2008** [comment]
![e](https://cloud.githubusercontent.com/assets/5414588/4602233/f4273a42-512b-11e4-93a6-c53b787ad1df.png)

something wrong?

**Comment by geraldstanje** [comment]
Can u use go qml from here? https://github.com/go-qml/qml and use gdb to debug it?

**Comment by oldtree2008** [comment]
I succeed in compiling with go1.4 . Maybe There is some wrong with go1.3 compiler.
