### ISSUE TITLE
win32下运行不起来

### ISSUE THREAD

**Issue by jiangyubao** [chai2010/qml#3]
你能否在vmware虚拟机上，重新安装一个winxp，然后把整个完成安装、配置、编译、打包过程写下来好让我们参考。

如果有必要，可以把vmware的磁盘文件上传到百度云盘，我们直接下载即可。

**Comment by chai2010** [comment]
你好，这个项目目前只是一个玩具。
如果是为了学习的话，从代码构建出能运行的示例程序的难度并不大。
如果是想实际写gui的话，不建议用go。

**Comment by jiangyubao** [comment]
no need such feature
